# Generated by Django 2.2.16 on 2022-06-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_create_Follow_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
