# Generated by Django 2.2.16 on 2022-06-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_changed_Comment_model_by_verbose_and_admin_site_register'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user_in_author'),
        ),
    ]
